package cineflix;

public class AdminMovieInventory extends javax.swing.JFrame {

    public AdminMovieInventory() {
        initComponents();
        this.setLocationRelativeTo(null); // Centers the JFrame.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain4 = new javax.swing.JPanel();
        pnlSideNav4 = new javax.swing.JPanel();
        lblTitle4 = new javax.swing.JLabel();
        lblHeader13 = new javax.swing.JLabel();
        lblHeader14 = new javax.swing.JLabel();
        btnMovieInventory4 = new javax.swing.JButton();
        btnUserProfiles4 = new javax.swing.JButton();
        btnRentalLogs4 = new javax.swing.JButton();
        btnPaymentReview4 = new javax.swing.JButton();
        btnLogout4 = new javax.swing.JButton();
        lblHeader15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CineFlix: MovieInventory");

        pnlMain4.setBackground(new java.awt.Color(255, 255, 255));

        pnlSideNav4.setBackground(new java.awt.Color(0, 0, 0));

        lblTitle4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblTitle4.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle4.setText("CineFlix");
        lblTitle4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblHeader13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblHeader13.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader13.setText("Dashboard");
        lblHeader13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblHeader14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblHeader14.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader14.setText("Admin");
        lblHeader14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnMovieInventory4.setBackground(new java.awt.Color(255, 255, 255));
        btnMovieInventory4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMovieInventory4.setForeground(new java.awt.Color(0, 0, 0));
        btnMovieInventory4.setText("Movie Inventory");
        btnMovieInventory4.setFocusable(false);
        btnMovieInventory4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovieInventory4ActionPerformed(evt);
            }
        });

        btnUserProfiles4.setBackground(new java.awt.Color(0, 0, 0));
        btnUserProfiles4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUserProfiles4.setForeground(new java.awt.Color(255, 255, 255));
        btnUserProfiles4.setText("User Profiles");
        btnUserProfiles4.setFocusable(false);
        btnUserProfiles4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserProfiles4ActionPerformed(evt);
            }
        });

        btnRentalLogs4.setBackground(new java.awt.Color(0, 0, 0));
        btnRentalLogs4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRentalLogs4.setForeground(new java.awt.Color(255, 255, 255));
        btnRentalLogs4.setText("Rental Logs");
        btnRentalLogs4.setFocusable(false);
        btnRentalLogs4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentalLogs4ActionPerformed(evt);
            }
        });

        btnPaymentReview4.setBackground(new java.awt.Color(0, 0, 0));
        btnPaymentReview4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPaymentReview4.setForeground(new java.awt.Color(255, 255, 255));
        btnPaymentReview4.setText("Payment Review");
        btnPaymentReview4.setFocusable(false);
        btnPaymentReview4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentReview4ActionPerformed(evt);
            }
        });

        btnLogout4.setBackground(new java.awt.Color(0, 0, 0));
        btnLogout4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLogout4.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout4.setText("Logout");
        btnLogout4.setFocusable(false);
        btnLogout4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout4ActionPerformed(evt);
            }
        });

        lblHeader15.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblHeader15.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader15.setText("Welcome, Admin");
        lblHeader15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnlSideNav4Layout = new javax.swing.GroupLayout(pnlSideNav4);
        pnlSideNav4.setLayout(pnlSideNav4Layout);
        pnlSideNav4Layout.setHorizontalGroup(
            pnlSideNav4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideNav4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlSideNav4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblHeader13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHeader14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitle4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeader15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(btnMovieInventory4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnUserProfiles4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRentalLogs4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPaymentReview4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogout4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlSideNav4Layout.setVerticalGroup(
            pnlSideNav4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideNav4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitle4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeader14, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeader13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHeader15)
                .addGap(44, 44, 44)
                .addComponent(btnMovieInventory4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUserProfiles4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRentalLogs4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPaymentReview4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogout4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMain4Layout = new javax.swing.GroupLayout(pnlMain4);
        pnlMain4.setLayout(pnlMain4Layout);
        pnlMain4Layout.setHorizontalGroup(
            pnlMain4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMain4Layout.createSequentialGroup()
                .addComponent(pnlSideNav4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 676, Short.MAX_VALUE))
        );
        pnlMain4Layout.setVerticalGroup(
            pnlMain4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSideNav4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogout4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout4ActionPerformed
        ActiveSession.clearSession(); // Clears active session.
        new Login().setVisible(true); // Returns to login frame.
        this.dispose();
    }//GEN-LAST:event_btnLogout4ActionPerformed

    private void btnPaymentReview4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentReview4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPaymentReview4ActionPerformed

    private void btnRentalLogs4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentalLogs4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRentalLogs4ActionPerformed

    private void btnUserProfiles4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserProfiles4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUserProfiles4ActionPerformed

    private void btnMovieInventory4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovieInventory4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMovieInventory4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMovieInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMovieInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMovieInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMovieInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMovieInventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout4;
    private javax.swing.JButton btnMovieInventory4;
    private javax.swing.JButton btnPaymentReview4;
    private javax.swing.JButton btnRentalLogs4;
    private javax.swing.JButton btnUserProfiles4;
    private javax.swing.JLabel lblHeader13;
    private javax.swing.JLabel lblHeader14;
    private javax.swing.JLabel lblHeader15;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JPanel pnlMain4;
    private javax.swing.JPanel pnlSideNav4;
    // End of variables declaration//GEN-END:variables
}
